tophub:
  enabled: true
  entry: "https://tophub.today/c/news?q=滚动新闻"
  frequencySec: 30

rss:
  - id: gov_pbc
    name: 中国人民银行-新闻稿
    enabled: false
    entry: "https://www.pbc.gov.cn/rmyh/105208/105216/index.html"
    type: A
    frequencySec: 60
  - id: shanghai_release
    name: 上海发布
    enabled: false
    entry: "https://rss.any/site/shanghai"
    type: C
    frequencySec: 120
html:
  - id: chinanews
    name: 中国新闻网-首页
    enabled: true
    entry: "https://www.chinanews.com.cn/index.shtml?14676=fsfdod"
    type: B
    frequencySec: 60
  - id: people
    name: 人民网-首页
    enabled: true
    entry: "https://www.people.com.cn/"
    type: A
    frequencySec: 60
    allowedHosts: ["people.com.cn"]
    hrefPatterns: [".*\\.html$", "/n1/\\d{4}/\\d{4}/c.*\\.html$"]
  - id: xinhuanet
    name: 新华网-首页
    enabled: true
    entry: "https://www.xinhuanet.com/"
    type: A
    frequencySec: 60
    allowedHosts: ["xinhuanet.com"]
    hrefPatterns: [".*\\.html$"]
  - id: cctv
    name: 央视网-首页
    enabled: true
    entry: "https://www.cctv.com/"
    type: A
    frequencySec: 60
    allowedHosts: ["cctv.com", "cctv.cn", "cntv.cn"]
    hrefPatterns: [".*\\.s?html$"]
  - id: china_com_cn
    name: 中国网-首页
    enabled: true
    entry: "http://www.china.com.cn/"
    type: A
    frequencySec: 60
    allowedHosts: ["china.com.cn"]
    hrefPatterns: [".*\\.html$"]
  - id: gmw
    name: 光明网-首页
    enabled: true
    entry: "https://www.gmw.cn/"
    type: A
    frequencySec: 60
    allowedHosts: ["gmw.cn"]
    hrefPatterns: [".*\\.html$"]
  - id: thepaper
    name: 澎湃新闻-首页
    enabled: true
    entry: "https://www.thepaper.cn/"
    type: B
    frequencySec: 60
    allowedHosts: ["thepaper.cn"]
    hrefPatterns: ["/newsDetail_forward_\\d+"]
  - id: yicai
    name: 第一财经-首页
    enabled: true
    entry: "https://www.yicai.com/"
    type: B
    frequencySec: 60
    allowedHosts: ["yicai.com"]
    hrefPatterns: ["/news/\\d{4}-\\d{2}-\\d{2}/[A-Za-z0-9_-]+\\.html$"]

